name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Deploy
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to Hostinger
              uses: easingthemes/ftp-publish-action@v2
              with:
                  ftp-server: ${{ secrets.FTP_SERVER }}
                  ftp-username: ${{ secrets.FTP_USERNAME }}
                  ftp-password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./dist
                  remote-dir: /public_html
